// import Newsletter from './components/layout/newsletter/newsletter'
'use client'
import "src/app/globals.css";
import { Roboto, Yellowtail, Open_Sans } from "next/font/google";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Provider } from "react-redux";
import store from "./reduxt_store/store";
// import Footer from "./components/layout/Footer/Footer";
// import store from "./reduxt_store/store"

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--roboto",
});
const yellowTail = Yellowtail({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--yellowTail",
});

const openSans = Open_Sans({
  weight: ["300", "400", "500", "600", "700", "800"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--openSans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${openSans.variable} ${yellowTail.variable}`}
      >
         <QueryClientProvider client={new QueryClient()}>
         <Provider store={store}>
          {children}
        </Provider>
         </QueryClientProvider>
      </body>
    </html>
  );
}
