// import Newsletter from './components/layout/newsletter/newsletter'
"use client";
import "src/app/globals.css";
import { Roboto, Yellowtail, Open_Sans } from "next/font/google";

import { Provider } from "react-redux";
import store from "../../reduxt_store/store";
import { SideBar } from "./components/layout/slideBar/SideBar";
// import Footer from "./components/layout/Footer/Footer";
// import store from "./reduxt_store/store"

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--roboto",
});
const yellowTail = Yellowtail({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--yellowTail",
});

const openSans = Open_Sans({
  weight: ["300", "400", "500", "600", "700", "800"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--openSans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${openSans.variable} ${yellowTail.variable}`}
      >
        <Provider store={store}>
          <div className="flex">
            <SideBar />
            <div className="flex-1">{children}</div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
